# Generated by Django 6.0 on 2025-12-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variations',
            new_name='Variation',
        ),
    ]
